version: '3.6'
services:

  redis-rdb:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./redis-rdb/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
    networks:
        - projector-queue 
        
  redis-aof:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./redis-aof/redis.conf:/usr/local/etc/redis/redis.conf    
    ports:
      - "6381:6379"
    networks:
        - projector-queue 

  beanstalkd:
    image: schickling/beanstalkd 
    ports:
      - "11300:11300" 
    networks:
        - projector-queue     

networks:
  projector-queue:
    driver: bridge