version: '3.6'
services:

  bind:
    image: sameersbn/bind:9.16.1-20200524
    networks:
      ddos:
        ipv4_address: 192.168.56.2
    ports:
    - 53:53/udp
    - 53:53/tcp
    - 10000:10000/tcp
    volumes:
    - ./bind:/data

  app:
    build:
      context: ../src
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      ddos:
        ipv4_address: 192.168.56.3

  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
     - 80:80
    networks:
      ddos:
        ipv4_address: 192.168.56.4
    volumes:
      - ./nginx/favicon.ico:/usr/share/nginx/html/favicon.ico
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  ddos:
    build:
      context: hping
      dockerfile: Dockerfile
    depends_on:
      - nginx  
    networks:
      ddos:
        ipv4_address: 192.168.56.5
    command: "hping3 --udp -i u100  localhost -p 80"

networks:
  ddos:
    driver: bridge
    ipam:
     config:
     - subnet: 192.168.56.0/24
       gateway: 192.168.56.1