filebeat.modules:
  #Filebeat system module consumes logs from host OS through a mounted volume
  - module: system
    syslog:
      var.paths: ["/var/log/host/system.log*"]
  #Mysql module consumes error and mysql-slow logs from mounted volume
  - module: mysql
    error:
      var.paths: ["/var/log/mysql/error.log*"]
    slowlog:
      var.paths: ["/var/log/mysql/mysqld_slow.log*"]
#All data to indexed to Elasticsearch
output.elasticsearch:
  hosts: ["http://localhost:9200"]  